Mark unused private field as maybe_unused
Reported by clang-r563880:

frameworks/av/services/camera/virtualcamera/VirtualCameraDevice.h:157:14: error: private field 'mPerFrameCameraMetadataEnabled' is not used [-Werror,-Wunused-private-field]
  157 |   const bool mPerFrameCameraMetadataEnabled;
      |              ^

Test: presubmit
Flag: EXEMPT, dead code cleanup
Change-Id: I3434e3c0a6448f0ddf007d3f15f457f35da96b58